id: azure-access-tokens

info:
  name: Azure Access Tokens - Detect
  author: m4lwhere
  severity: high
  description: Azure Access Token found via /.azure/accessTokens.json endpoint.
  reference:
    - https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L
    cvss-score: 9.4
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
  tags: config,exposure,azure,credential

http:
  - method: GET
    path:
      - "{{BaseURL}}/.azure/accessTokens.json"

    matchers:
      - type: word
        words:
          - 'accessToken'
          - 'identityProvider'
          - 'refreshToken'
        condition: and
        part: body

    extractors:
      - type: regex
        part: body
        regex:
          - "refreshToken\": \".*"
